package me.aiglez.service.ui.templates

import me.aiglez.service.domain.models.TemplateBarcodeFormat
import me.aiglez.service.domain.models.TemplateElement

internal const val EditorTestSchemaId = "test_service_order"

internal fun List<TemplateElement>.withEditorTestElementsIfEmpty(): List<TemplateElement> {
    if (isNotEmpty()) return this
    return listOf(
        TemplateElement.Rectangle(
            id = "test-header-band",
            name = "Header band",
            x = 48f,
            y = 48f,
            width = 500f,
            height = 86f,
            zIndex = 1,
            fillColor = "#EFF6FF",
            borderColor = "#93C5FD",
            borderWidth = 1f,
            borderRadius = 8f,
        ),
        TemplateElement.Text(
            id = "test-title",
            name = "Static heading",
            x = 72f,
            y = 66f,
            width = 250f,
            height = 34f,
            zIndex = 2,
            staticText = "Service order test sheet",
            fontSize = 20f,
            fontWeight = 700,
            color = "#1E3A8A",
        ),
        TemplateElement.Text(
            id = "test-order-number",
            name = "Bound order number",
            x = 72f,
            y = 104f,
            width = 250f,
            height = 24f,
            zIndex = 3,
            staticText = "Order {{ data.order_number }}",
            placeholderTag = "[DataRecord:order_number]",
            fontSize = 13f,
            color = "#1F2937",
        ),
        TemplateElement.Text(
            id = "test-total",
            name = "Bound currency total",
            x = 346f,
            y = 66f,
            width = 170f,
            height = 34f,
            zIndex = 4,
            staticText = "{{ currency(data.total_amount, \"USD\") }}",
            placeholderTag = "[DataRecord:total_amount]",
            fontSize = 18f,
            fontWeight = 700,
            textAlign = "right",
            color = "#166534",
        ),
        TemplateElement.Text(
            id = "test-conditional-priority",
            name = "Conditional priority text",
            x = 346f,
            y = 104f,
            width = 170f,
            height = 24f,
            zIndex = 5,
            staticText = "{{ if(gte(data.priority_level, 4), \"Priority order\", \"Standard order\") }}",
            fontSize = 12f,
            fontWeight = 600,
            textAlign = "right",
            color = "#B45309",
        ),
        TemplateElement.Rectangle(
            id = "test-customer-card",
            name = "Customer card shape",
            x = 48f,
            y = 158f,
            width = 240f,
            height = 116f,
            zIndex = 6,
            fillColor = "#F8FAFC",
            borderColor = "#CBD5E1",
            borderWidth = 1f,
            borderRadius = 8f,
        ),
        TemplateElement.Text(
            id = "test-customer-label",
            name = "Customer label",
            x = 68f,
            y = 176f,
            width = 190f,
            height = 20f,
            zIndex = 7,
            staticText = "Customer",
            fontSize = 11f,
            fontWeight = 700,
            color = "#64748B",
        ),
        TemplateElement.Text(
            id = "test-customer-name",
            name = "Bound customer name",
            x = 68f,
            y = 202f,
            width = 190f,
            height = 28f,
            zIndex = 8,
            staticText = "{{ data.customer_name }}",
            placeholderTag = "[DataRecord:customer_name]",
            fontSize = 17f,
            fontWeight = 700,
            color = "#111827",
        ),
        TemplateElement.Text(
            id = "test-customer-email",
            name = "Bound customer email",
            x = 68f,
            y = 236f,
            width = 190f,
            height = 22f,
            zIndex = 9,
            staticText = "{{ lower(data.customer_email) }}",
            placeholderTag = "[DataRecord:customer_email]",
            fontSize = 12f,
            color = "#475569",
        ),
        TemplateElement.Rectangle(
            id = "test-status-pill",
            name = "Conditional status pill",
            x = 328f,
            y = 158f,
            width = 220f,
            height = 52f,
            zIndex = 10,
            fillColor = "#FEF3C7",
            borderColor = "#F59E0B",
            borderWidth = 1f,
            borderRadius = 8f,
        ),
        TemplateElement.Text(
            id = "test-status-text",
            name = "Conditional amount text",
            x = 346f,
            y = 174f,
            width = 184f,
            height = 22f,
            zIndex = 11,
            staticText = "{{ if(gt(data.total_amount, 500), \"High value\", \"Regular value\") }}",
            fontSize = 14f,
            fontWeight = 700,
            textAlign = "center",
            color = "#92400E",
        ),
        TemplateElement.List(
            id = "test-service-items-list",
            name = "Bound service item list",
            x = 48f,
            y = 304f,
            width = 240f,
            height = 138f,
            zIndex = 12,
            fieldSlug = "service_items",
            prefix = "- ",
            itemSeparator = ",",
            maxItems = 8,
            columns = 1,
            itemSpacing = 6f,
            padding = 12f,
            fontSize = 12f,
            color = "#111827",
            backgroundColor = "#F0FDF4",
            borderColor = "#86EFAC",
            borderWidth = 1f,
            borderRadius = 8f,
        ),
        TemplateElement.Circle(
            id = "test-circle-accent",
            name = "Circle accent",
            x = 318f,
            y = 300f,
            width = 70f,
            height = 70f,
            zIndex = 13,
            fillColor = "#FCE7F3",
            borderColor = "#DB2777",
            borderWidth = 2f,
        ),
        TemplateElement.Rectangle(
            id = "test-overlap-front",
            name = "Overlap shape",
            x = 358f,
            y = 334f,
            width = 96f,
            height = 64f,
            zIndex = 14,
            fillColor = "#EDE9FE",
            borderColor = "#7C3AED",
            borderWidth = 2f,
            borderRadius = 6f,
            opacity = 0.9f,
        ),
        TemplateElement.QRCode(
            id = "test-bound-qr",
            name = "Bound QR code",
            x = 48f,
            y = 484f,
            width = 118f,
            height = 118f,
            zIndex = 15,
            text = "{{ data.qr_payload }}",
            borderColor = "#CBD5E1",
            borderWidth = 1f,
        ),
        TemplateElement.Text(
            id = "test-qr-caption",
            name = "QR caption",
            x = 48f,
            y = 610f,
            width = 118f,
            height = 28f,
            zIndex = 16,
            staticText = "QR from record URL",
            fontSize = 10f,
            textAlign = "center",
            color = "#475569",
        ),
        TemplateElement.Barcode(
            id = "test-bound-barcode",
            name = "Bound barcode",
            x = 204f,
            y = 500f,
            width = 260f,
            height = 82f,
            zIndex = 17,
            text = "{{ data.tracking_code }}",
            format = TemplateBarcodeFormat.Code128,
            showText = true,
            borderColor = "#CBD5E1",
            borderWidth = 1f,
        ),
        TemplateElement.Text(
            id = "test-notes",
            name = "Bound notes with fallback",
            x = 48f,
            y = 674f,
            width = 500f,
            height = 54f,
            zIndex = 18,
            staticText = "Notes: {{ default(data.notes, \"No notes supplied\") }}",
            placeholderTag = "[DataRecord:notes]",
            fontSize = 12f,
            color = "#334155",
            backgroundColor = "#F8FAFC",
            padding = 8f,
            borderColor = "#E2E8F0",
            borderWidth = 1f,
            borderRadius = 6f,
        ),
        TemplateElement.Line(
            id = "test-line",
            name = "Footer divider",
            x1 = 48f,
            y1 = 760f,
            x2 = 548f,
            y2 = 760f,
            thickness = 3f,
            zIndex = 19,
        ),
    )
}



